### PR TITLE
Reuse messages in rzmq

### PR DESCRIPTION
**Pull request by mschubert**
This is a pull request for https://github.com/ropensci/rzmq/issues/38.

It contains the two new functions (and their `Rcpp` equivalents):

* `init.message` - create a ZMQ message object as an external pointer
* `send.message.object` - send a message object directly without copying its memory

It further makes the following (backwards-compatible) API changes:

* `init.context` now takes one (optional) argument `threads`, which is the number of threads the context should use

These changes allow the user to send messages multiple times without copying their memory after the message is initialized. Further, they are required to fix https://github.com/mschubert/clustermq/issues/19 and [#47](https://github.com/mschubert/clustermq/issues/47) (in short: big messages that are sent repeatedly are not collected quickly enough by the gc, which may cause R to take up the combined memory - in my case sometimes over 30 GB for 300 MB data).

For the message object itself, I have checked appropriate memory release with `valgrind`, with no reported leaks.

### CODE REVIEW

**Comment by mschubert** [comment]
@armstrtw @jeroen would be great if you could take a look!

**Comment by jeroen** [comment]
I'm going to leave this up to @armstrtw, he is more familiar with this code.

**Comment by armstrtw** [comment]
looks good.  you've tested on your use cases?

@jeroen what's the deal w/ the codecov tests?  I'm not really familiar w/ those.

**Comment by mschubert** [comment]
Yes, I've tested for my package and the memory issue is gone. I can add a unit test for usage if required.

Codecov I think is just the decreased test coverage because I provided code without a unit test (but most of the API doesn't have them).

**Comment by armstrtw** [comment]
great if you can add a unit test later.

thanks for the contribution.

**Comment by mschubert** [comment]
Great, thank you!

@jeroen, can you push to CRAN so I can release my updated pkg?

**Comment by jeroen** [comment]
I cannot release because your commit https://github.com/ropensci/rzmq/commit/23b639511f5785d83234a4ea17c537533d56ceee has broken the build for windows. See [install log](https://win-builder.r-project.org/NSZc71fBA7y3/00install.out). Can you fix this?

**Comment by jeroen** [comment]
I think you can simply revert that commit? The default SIGWINCH is always to ignore.

**Comment by mschubert** [comment]
When I sent the patch SIGWINCH was not ignored on Linux (and I'm pretty sure things haven't changed). I think a better option would be to `#ifdef` it, but I'll test this and get back to you tomorrow.

I'm surprised that it worked on Appveyor and failed on CRAN.

**Comment by jeroen** [comment]
I'm surprised about that too. I think it might have to do with the fact that CRAN runs a relatively old version of windows (server 2008) and travis uses a more recent version.

**Comment by jeroen** [comment]
Can you make sure the package passes on the CRAN win builder ?

**Comment by jeroen** [comment]
On cran now.

**Comment by mschubert** [comment]
Great, thank you!

**Pull request merged**
