### PR TITLE
Added get/set functionality for RCV_TIMEO.

### PR DESCRIPTION
**Pull request by bicarlsen**

### CODE REVIEW

**Comment by bicarlsen** [comment]
`src/symbols.rds` was removed during the build process. I'm not sure if this is important or how to generate it, if it is.

**Comment by bicarlsen** [comment]
I'm not sure why the Windows builds are failing. Any guidance would be appreciated.

**Comment by jeroen** [comment]
You can ignore the windows error, it is unrelated.

Did you test that you can call this function when the package is installed? I think it needs to be added to the export list in the NAMESPACE file?

**Comment by jeroen** [comment]
I also fixed the CI, so if you rebase your pr on the master branch, it will pass on Win.

**Comment by jeroen** [comment]
Thanks

**Comment by jeroen** [comment]
Would you like a CRAN release, or do you plan to add more things?

**Comment by jeroen** [comment]
Ok i have released a version to cran for you. You can send a pr to convert docs to roxygen if you like. I think there is even a package rd2roxygen that can help with that.

**Pull request merged**
