### PR TITLE
Install signal handler instead of IGN (#44)

### PR DESCRIPTION
**Pull request by mschubert**
Pull request for https://github.com/ropensci/rzmq/issues/44.

*work in progress*

### CODE REVIEW

**Comment by armstrtw** [comment]
thanks.

**Comment by mschubert** [comment]
Thank you, but I'm afraid the merge as a bit too quick

Please do not put this on CRAN yet, it needs more testing (and likely a couple of adjustments)

**Comment by jeroen** [comment]
Please be careful not to override R's internal signal handing. R has a built-in methods for catching SIGINT which is exposed via the `R_CheckUserInterrupt()` api. I think you should only use custom signal handlers if you are resetting them at the end of the function.

**Comment by mschubert** [comment]
Yes, that part is still missing - hence the *work in progress*

**Comment by jeroen** [comment]
OK I'm going to revert it in master :)

**Comment by jeroen** [comment]
I have removed the commit from the master branch. Can you send a new PR once it is done? Maybe keep the WIP in your private repo :)

**Comment by mschubert** [comment]
Ha, I thought that was a good way to have you two have a look at the current state, but next time I'll put a

**DO NOT MERGE YET**

in bold and blinking letters ;)

WIP is here: https://github.com/mschubert/rzmq/tree/signal

**Pull request merged**
